### ISSUE TITLE
quantos.org  报错, 无法注册新用户了~

### ISSUE THREAD

**Issue by ccoossdddffdd** [quantOS-org/TradeAPI#1]
![image](https://user-images.githubusercontent.com/120555/32998830-449ae6ae-cdd9-11e7-9af4-cdfcd70ba76a.png)

**Comment by tashaxing** [comment]
多谢反馈和支持，注册问题和函数问题已修复^_^

**Comment by ccoossdddffdd** [comment]
http://www.quantos.org/tradesim/trade.html

仿真交易这块怎么添改风控项目呢? 

另外能介绍下实时风控是如何确保即时准确的么?

**Comment by PKUJohnson** [comment]
谢谢关心.
目前风控设置界面尚未开放,我们尽快推出.
实时风控在内存中进行,订单发送前检查,所以可以做到实时准确.后续会有详细文档披露.
